factual:
  key: eXMwUZMBIrfW7ORstKjqxoZelkYRMmOwi6C7lRDt
  secret: htInMeU5AXUHdPuErx27W1MIj9MYeYzsG6DhhSV6

google:
  key: AIzaSyDxG-6sGqo6mwxmtKa2JAkxECAwCJVLE_M
  
semantics3:
  key: SEM3B2A0A629C02F78E9F3C71505E6F49C26
  secret: ZWRhNmNmNTIxZWUzMmIwMDZkOTljMDdhZTViODM4YmE
  
tmdb:
  key: a8ddb278788ceab2a58875b7f172c327