factual:
  key: eXMwUZMBIrfW7ORstKjqxoZelkYRMmOwi6C7lRDt
  secret: htInMeU5AXUHdPuErx27W1MIj9MYeYzsG6DhhSV6

google:
  key: AIzaSyDxG-6sGqo6mwxmtKa2JAkxECAwCJVLE_M
  
semantics3:
  key: SEM31558CA7AE793399241F600328698D16C
  secret: NzhlZTM1MjhjNjA0NjU2OGEzY2FkZTg3NmU1ODAwMGQ
  
tmdb:
  key: a8ddb278788ceab2a58875b7f172c327